version: 0.2

phases:
  install:
    commands:
      - php -v
  build:
    commands:
      - date
artifacts:
  files:
    - '**/*'
  base-directory: 'var/www/html/'
  name: build-artifact-name
  discard-paths: no
